# Generated by Django 4.2.7 on 2023-11-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelFormsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='date',
        ),
    ]
