# Generated by Django 4.2.7 on 2023-11-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokenProjectDRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretmessagemodel',
            old_name='Sender',
            new_name='sender',
        ),
    ]
