# Generated by Django 4.2.7 on 2023-11-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokenProjectDRF', '0002_rename_sender_secretmessagemodel_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretmessagemodel',
            old_name='contenct',
            new_name='content',
        ),
    ]
