# Generated by Django 4.2.6 on 2023-10-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='itemName',
        ),
    ]
