# Generated by Django 4.2.6 on 2023-10-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_rename_name_menu_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='age',
            field=models.IntegerField(default=5),
        ),
    ]
