# Generated by Django 4.2.6 on 2023-10-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_menu_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
