# Generated by Django 4.2.7 on 2024-01-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_bookin_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookin',
        ),
    ]
