# Generated by Django 5.0.1 on 2024-01-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_booking_bookin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookin',
            new_name='Booking',
        ),
    ]
