# Generated by Django 4.2.6 on 2023-10-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='donald', max_length=100)),
                ('books_by_him', models.CharField(default='The carizma myth', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookStoreDRF.authormodel')),
            ],
        ),
    ]
