# Generated by Django 4.2.7 on 2023-11-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegtables', models.CharField(max_length=255)),
                ('meat', models.CharField(max_length=255)),
            ],
        ),
    ]
